spring:
  application:
    name: ECommer
  datasource:
    url: jdbc:postgresql://localhost:3333/product_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
